### ISSUE TITLE
블로그 보고 왔습니다

### ISSUE THREAD

**Issue by hi-one-gg** [dwha/SimpleCudaNeuralNet#1]
잘봤습니다. 유익한 공부가 돼셨을것 같네요..ㅎㅎ
하나 궁금한게 있는데,
이렇게 구현시 파이썬과 비교해서 속도차이는 얼마나 나는지도 아시는지요? 

참고할만한 다른 글이라도 있으면 알려주시면 감사하겠습니다. 만약 빠르다면 씨플플로 개발해보려 기웃거리는 중입니다..ㅎㅎ

**Comment by dwha** [comment]
readme.md 의 Notes에 성능에 대한 언급이 있습니다. 해당 프로젝트가 공부를 위한 구현물이라 cudnn 수준의 최적화와는 상당한 거리가 있습니다.

**Comment by hi-one-gg** [comment]
> readme.md 의 Notes에 성능에 대한 언급이 있습니다. 해당 프로젝트가 공부를 위한 구현물이라 cudnn 수준의 최적화와는 상당한 거리가 있습니다.

아하 감사합니다ㅎㅎ 읽는 중에 아래 내용이 매우 흥미로운데요~
"Training performance is not comparable to PyTorch. PyTorch is much faster (x7~) to train the same model."

같은 모델을 파이토치에서 학습할 시 7배나 더 빠르나요....?
와.......... 왜 이런 결과가 나왔는지 매우 궁금해지네요.. 🤔
현 레포가 cudnn을 적용하지 않아서 그런것일까요?

**Comment by dwha** [comment]
맞습니다. 이 구현은 CUDA로 최소한의 NN를 최소한의 최적화로 진행한 것이고,  cuDNN은 GPU 최고 성능을 뽑을 수 있도록 전문가들이 최적화한 구현일테니 애초 비교가 될 수는 없겠지요.

**Comment by hi-one-gg** [comment]
> 맞습니다. 이 구현은 CUDA로 최소한의 NN를 최소한의 최적화로 진행한 것이고, cuDNN은 GPU 최고 성능을 뽑을 수 있도록 전문가들이 최적화한 구현일테니 애초 비교가 될 수는 없겠지요.

감사합니다. 답변해주시는 것들을 보며 드는생각이, Cuda와 Cudnn을 사용하는 파이썬 프로그램이 c++로 구현한 딥러닝에 비해 전혀 느리지 않을 것이라는 생각이 드네요.. 배포의 목적이 아니라면 굳이 c++로 딥러닝을 설계하지 않아도 될 거라는 생각이 드네요...

파이썬이 c++보다 느리다고 해서 c++로 딥러닝을 구현해보려한건데 gpu연산에 있어서는 씨플플이든 파이썬이든 속도가 같을거라고 판단이 서는데 혹시 이에 대해 어떻게 생각하시는지 의견을 들어보고 싶습니다. 

감사합니다.

**Comment by dwha** [comment]
PyTorch가 파이썬에서 돌아가지만 내부  핵심코드들은 거의 C++ 로 작성되었을 겁니다.(cuDNN 포함) 단순 wrapping해서 파이썬에서 노출되는 방식이기 때문에 개인이 더 빠르게 짜기 쉽지 않을겁니다.

**Comment by hi-one-gg** [comment]
> PyTorch가 파이썬에서 돌아가지만 내부 핵심코드들은 거의 C++ 로 작성되었을 겁니다.(cuDNN 포함) 단순 wrapping해서 파이썬에서 노출되는 방식이기 때문에 개인이 더 빠르게 짜기 쉽지 않을겁니다.

의견 감사합니다🙂. 이만 종료하겠습니다.
